// Generated by Wrangler on Fri Aug 07 2026 01:02:50 GMT+0530 (India Standard Time)
// by running `wrangler types`

interface Env {
	UNMASK_TERMS_CACHE: KVNamespace;
	BACKEND_API_URL: "http://127.0.0.1:8001";
}
