/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Document
         * @description Accepts file upload (PDF/Word/Text) or raw text input.
         *     Kicks off RAG pipeline in background.
         */
        post: operations["upload_document_api_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document
         * @description Retrieves document processing status and full analysis once completed.
         */
        get: operations["get_document_api_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/demo/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Demo Documents
         * @description Returns static pre-analyzed documents for instant homepage CTA demonstration.
         */
        get: operations["get_demo_documents_api_documents_demo_all_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Simple keep-alive health check endpoint.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyzedClause */
        AnalyzedClause: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            category: components["schemas"]["ClauseCategory"];
            riskLevel: components["schemas"]["RiskLevel"];
            /** Confidence */
            confidence: number;
            /** Originaltext */
            originalText: string;
            /** Simplifiedtext */
            simplifiedText: string;
            /** Explanation */
            explanation: string;
            /** Ragcomparison */
            ragComparison: string;
            /**
             * Comparedreferenceids
             * @default []
             */
            comparedReferenceIds: string[];
            /** Sectionlocation */
            sectionLocation: string;
            /**
             * Ruleflags
             * @default []
             */
            ruleFlags: string[];
        };
        /** Body_upload_document_api_documents_post */
        Body_upload_document_api_documents_post: {
            /** File */
            file?: string | null;
            /** Raw Text */
            raw_text?: string | null;
            /** Url */
            url?: string | null;
            /**
             * Document Type
             * @default custom
             */
            document_type: string;
        };
        /**
         * ClauseCategory
         * @enum {string}
         */
        ClauseCategory: "auto_renewal" | "arbitration_dispute_resolution" | "unilateral_modification" | "liability_limitation" | "data_collection_sharing" | "termination_conditions" | "fee_structures_penalties" | "governing_law_venue" | "privacy_consent_mechanisms";
        /** DocumentAnalysisResult */
        DocumentAnalysisResult: {
            /** Id */
            id: string;
            status: components["schemas"]["DocumentStatus"];
            /** Filename */
            filename: string;
            /**
             * Documenttype
             * @default custom
             */
            documentType: string;
            /** Uploaddate */
            uploadDate: string;
            /** Healthscore */
            healthScore?: number | null;
            /** Summary */
            summary?: string | null;
            /**
             * Clauses
             * @default []
             */
            clauses: components["schemas"]["AnalyzedClause"][];
            /**
             * Toprisks
             * @default []
             */
            topRisks: components["schemas"]["AnalyzedClause"][];
            /**
             * Categorybreakdown
             * @default {}
             */
            categoryBreakdown: {
                [key: string]: number;
            };
            /** Processingtimeseconds */
            processingTimeSeconds?: number | null;
            /** Errormessage */
            errorMessage?: string | null;
            /**
             * Disclaimer
             * @default This analysis is for informational purposes only and does not constitute legal advice. Always consult a qualified attorney before making legal decisions based on contract analysis.
             */
            disclaimer: string;
        };
        /**
         * DocumentStatus
         * @enum {string}
         */
        DocumentStatus: "processing" | "done" | "error";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * RiskLevel
         * @enum {string}
         */
        RiskLevel: "standard" | "cautionary" | "risky";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    upload_document_api_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentAnalysisResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_demo_documents_api_documents_demo_all_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
